platform :ios, '13.0'
use_frameworks!

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'ScanditCapacitorDatacaptureText', :path => '../../node_modules/scandit-capacitor-datacapture-text'
  pod 'ScanditCapacitorDatacaptureId', :path => '../../node_modules/scandit-capacitor-datacapture-id'
  pod 'ScanditCapacitorDatacaptureCore', :path => '../../node_modules/scandit-capacitor-datacapture-core'
end


target 'App' do
  capacitor_pods
  # Add your Pods here
end
